title: <p align="center"> Amey Talkatkar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/ameycancode">GitHub</a>
 
  <br>  
  I'm working on Scripting Languages like Perl, Python, Unix Shell Scripting.
  Have experience in developing enterprise automation softwares that are used by Fortun 500 companies.

  <br>
  </p>



theme: jekyll-theme-minimal
